# Generated by Django 4.1.3 on 2022-11-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='creator',
        ),
    ]
