# Generated by Django 4.1.3 on 2022-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_label_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(null=True, through='task_manager.labels_of_task', to='task_manager.label', verbose_name='Labels'),
        ),
    ]
